---

git_repo: git@github.com:paolopaolopaolo/dolphin-attacks.git
repo_name: dolphinattacks

project_name: dolphinattacks
application_name: dolphinattacks

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDA9cIViJF0xRDCRc2paIHACix43HAjj8A/A6hxbMkvna8QLUUK2OKImVt8lQvwlZ3EB9eWO9PGyFgV2H+BOubphDn7wvrwsle2Bz5cf1PIgYMOAIXcdLUJLmDxc26473jsy8iBPKddPoHQ6E4f5icWNt+LP1haXzHtMOOmnQW6XD7ThUJybqosHrc9H8ELOfsk6SO99yCg7m21NSvoX5c+p2NONrSOwc81xXP4mltpWL3HbGmUo5SO1FF8924lf8D22ENprUKkBFyKCyz0oUPN+MElkn4daGkhfa4uTkbL4d5sVM6ZONyc0YeikEiVQIyIuNeYyJB1IzWD40QI2ueLI+R0vE0vN1eVMrRLheqHSlBLZ4rjbDkqSI1x13w4UuDT3er85QIODoawSiLXYzg5kymy14D4PxY8dbr5S1lKzi5lAugrudAf9+Qz5Q3De32dWQv1M/vnC2Zjw6FicsAo61ZK59WznMg8k5RVuggBre36+ANnB8oU1bJgn02F9lsj5kMaoBEBV8uCHVnRlE0rcoduc3BK1PGa8a8XbbU4f9OMOsKvDQsAg/B+go9aQ2++QxhaV1i/mHxFhN/rZ1TFwwoqwxXb9UVZQvX+3fox9uTN0vHAew0d/5TLe24m5dEBILPjPtaJCOBKq4CwVqKt9biD+g+XmJR1M8uIKNPKRw==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAwPXCFYiRdMUQwkXNqWiBwAoseNxwI4/APwOocWzJL52vEC1F
  CtjiiJlbfJUL8JWdxAfXljvTxshYFdh/gTrm6YQ5+8L68LJXtgc+XH9TyIGDDgCF
  3HS1CS5g8XNuuO947MvIgTynXT6B0OhOH+YnFjbfiz9YWl8x7TDjpp0Fulw+04VC
  cm6qLB63PR/BCzn7JOkjvfcgoO5ttTUr6F+XPqdjTja0jsHPNcVz+JpbaVi9x2xp
  lKOUjtRRfPduJX/A9thDaa1CpARcigss9KFDzfjBJZJ+HWhpIX2uLk5Gy+HebFTO
  mTjcnNGHopBIlUCMiLjXmMiQdSM1g+NECNrniyPkdLxNLzdXlTK0S4Xqh0pQS2eK
  42w5KkiNcdd8OFLg093q/OUCDg6GsEoi12M4OZMpsteA+D8WPHW6+UtZSs4uZQLo
  K7nQH/fkM+UNw3t9nVkL9TP75wtmY8OhYnLAKOtWSufVs5zIPJOUVboIAa3t+vgD
  ZwfKFNWyYJ9NhfZbI+ZDGqARAVfLgh1Z0ZRNK3KHbnNwStTxmvGvF221OH/TjDrC
  rw0LAIPwfoKPWkNvvkMYWldYv5h8RYTf62dUxcMKKsMV2/VFWUL1/t36MfbkzdLx
  wHsNHf+Uy3tuJuXRASCz4z7WiQjgSquAsFairfW4g/oPl5iUdTPLiCjTykcCAwEA
  AQKCAgEAscm+adjLLKvmJRnrxItmAWteTn3NVPa+S1Ezgk6ZkCXZhy4uzy/GidXD
  VaZ+uc0g793J5cJ5/k3Z20b/NDLxT3dldXLRg7TO3AkQjGlE6Rlrhxs0O0vNAgiZ
  id6xxfPfl06sD2ezTVaqhbGFSh7lJLKqhcJ3xcywU7sYBgvnmy4jNQEzl/wfD0e9
  zbPUSmPB4uBs7jsk9SK6MpwrOI/a6v+PoCEHfAFWylSD5itSzl3VfkmFfk66Ml+u
  NVZFRofPY6Efe98H59ec7BQf98Yek0j/rX6sdKwfMZx7QG8fC/uw1F/Pe53IpzTn
  pAEM33f6BH9LJpqlf0hRppNfvEj1zMGq9EFp20BJsgPOqHm3O8T+uketicipr5ZZ
  0iiUlwkfIljkpV56GACDF0LuRZ3O+lhEctaPNr/kLOPzk7/EGyKIPznDY1Svr0Tf
  foVv6PxcbYfZMVKyXDyTg/eya5hqZsphFMeXHmtB4jOofURYkT8vkdXSwpZrFG/9
  Jwdzxb0llLQAYZkUV7urRxTAL2cwiEXJA0/oUtw/MqexGWCsBgsfUeyMsUgqFK+Q
  gElY/VUMCQoBIf1MjMSBzz2qa4kuxa8Izke20X5SDfFK/7kga5btimwqXsNVecPX
  qzg5HAPvcEpfFzfjsCVeSpxzKZFZJ/amMEDP8MlwXv3FqY0U5gECggEBAMZTQ8jf
  badCFUxlecdaQax7V2ouutUExlrepOVKHhsN72WwjfsObK92PFK3aV5yEVOn3wKx
  cKfCYQGAzlsZpPyRSBSIBPPV/HV2HcDKGd5OHc4TMwjZTFdVDhrmgM9noihdDoIw
  6whH2orBJbDif9c5wyw0ozMyeO9LvqTA0w5+u/6eVmKd335xjz/7ngL+E/lEKO8z
  Ge98RGQ0ka96W/DwVeuIvNfwgwEdLYN+qjxyNKu8TVhQf9LR2CPM1rSM31SEz7IJ
  o2jrTE+/S0BcFbb9gwxOyh20LqQGLobBf+ZxkmBHxe62gTEJmOBzGdGEBHeWjArP
  yD3e6ox9B1p1Rl8CggEBAPkTEL7vMdm6qX3XyfnZthlPdjN1DAHBPllcanFrwv7A
  Hz8VZ3Bl5pVZ4fcf9rfDv56dDI96I9AxWBiEATUQuq7efwIr7sb7V8n/pAbDiJhq
  EEeEhb9EDN68RTIzERMtHfCoykQVfudkPkNjDnjXizwK1fVv952XBTJvN7vCOwqt
  zA2KWyCYgSdYlJPOg7bjcZip7nMYjLjiNscezu1IZku16Zu/UGf/XuCvBtBKC61p
  ZjmSZtAqh5ow7F0qyIHUdDYF14l/KHM9GhhqdBtg58iu2YWzVN13EJ+5Ay4K2pAU
  MDx9m8qEQMi392liN6vF1G54oRRI9elJya2HC2BZ9RkCggEASl7vDGS8ufwOAJgN
  ErTF6+hU33ymkzs3JtxW+aTRpVOUco3CsGK4XxP3iw08di5QUQ6ikl/33vEFb4rd
  10vGku/oF8rqEIYuJd4lSiZ/jN2+T4jjmm3iMt2ybGQD6cLzDC/ZQPkXKgPH8EB9
  4dcOGaePiQQ0Lv6+Wv4Mf7vPaaAc316BBnotVT1Aer3ggz7EPrVQpGKFV0lCXFFa
  UHOSBsgZcDnWlyOZ/ND0QFs/e2tYVQ5H8tY9GNGYO9SUryAkn40uVZVHshCKjV0u
  2vOtMPHgMr1ZDcqDsv6ec+ocDE6KlZBUqS/HQpxWt9Rx2h+njTDnUyaX8JunWQeJ
  umJAAQKCAQBx01KtzyYa+IEIr5rwAZyEiJnd/jmUe7mAoQlL+BFO1oHxFFkHNqpf
  yonHo+XeKSji1aat0wWW2VYHLhxXIeQOkkO8vFMMwERoXdmZ9bXw4Ve7N0bgF7tB
  9wwwWsIM32t1Vc3Ju4EZQehqZ1RvySEqOVF6LsccT63iVI1F0wekY7SC452tkcRE
  NOkBezkaVWrOd6ovEyMMQuUBroSmT5XgN6wgrxeRz1SOna4hdhVMFITQ/qTZsPXz
  czQxh6HGI09QeO79OQ1FTMEmM1AISwrh3XYu8btw0j7Yn3Zijjc/7Nn2avjNXg81
  K0137Zi/eVMRgTMr0AQBruTp1nNOfw3RAoIBAQCDg71DDXA513L3BqUTBvkbaMDT
  0EdnSCrDNJLqbxKXn2wAL6k4sXj/hORm2I2PPsZ4JYotmsX3OmBO8LjWGE18BvS/
  1CYB+cwZnWeqLolG5n/q07y5u685miFkvd6zcng+lZ4Eg4dY2vU696+VhejVgR46
  eYrtg/bX7DGI5qGQ5TfQV3h1bYlQJhpHjTHGytXmWnc8Y0qxZDiwNwETHJ8q9G3l
  MI9v4UdspNdLJFb1GreK2BZnSWT+uO9751w44qJGq2MVqUGPU6W/y+NeSyTt2Efa
  5ioupdabZEKFFRj6nOiKQ5vK7UKYEXJjhlQhgsgw62wFvXd/1k4jHFmNSLFt
  -----END RSA PRIVATE KEY-----

